#
# project_pacman - pacman.conf
#
# User-space pacman configuration
# No root required - everything under ~/pacman/
#

[options]
RootDir     = /Users/revanthnemtoo/pacman/root
DBPath      = /Users/revanthnemtoo/project_pacman/repo/db/
CacheDir    = /Users/revanthnemtoo/project_pacman/cache/
LogFile     = /Users/revanthnemtoo/project_pacman/logs/pacman.log
GPGDir      = /Users/revanthnemtoo/pacman/etc/pacman.d/gnupg/
HookDir     = /Users/revanthnemtoo/pacman/etc/pacman.d/hooks/

Architecture = auto
SigLevel = Never
LocalFileSigLevel = Never
RemoteFileSigLevel = Never

ParallelDownloads = 5
